INFRA-271:OCD3 to have an 'initializer' project type (temporary solution)
mekomsolutions/openmrs-cd pull request #17
Opened 2021-03-13 14:54 UTC by enyachoke

…ion)

2021-03-15 07:39 UTC, mks-d reviewed
Thanks @enyachoke, great work.

I'm mostly good with it, I guess we just need to review the landing README.

2021-03-15 07:39 UTC, mks-d commented on docker-compose.yaml
> +     - ./data/app_data:/var/lib/openmrs_cd/app_data
@enyachoke thanks for that!

2021-03-15 07:39 UTC, mks-d commented on README.md
> +
@rbuisson I guess the landing README will have to be reviewed to put this in the right place?

2021-03-17 18:48 UTC, rbuisson requested changes
Thanks!
Could you update the [config.xml](https://github.com/mekomsolutions/openmrs-cd/blob/fd8667ad248fe6387de8f3fb507b2d4cfc6e8636/jenkins/jenkins_home/jobs/pipeline1/config.xml#L25) to add the new 'initializer' type.

Otherwise, looks good (and works good) 👍🏻

2021-03-19 17:40 UTC, rbuisson approved these changes
Thanks!

2021-03-19 17:41 UTC, merged