WIP: Create env file when only artifacts change
mekomsolutions/openmrs-cd pull request #46
Opened 2024-06-14 08:13 UTC by enyachoke

2024-06-14 10:00 UTC, rbuisson reviewed
This looks good to me at first glance.
If that works, then we're good.

2024-06-14 10:07 UTC, rbuisson commented
@enyachoke  could you reuse the logic from this function, instead of copying it?
 https://github.com/mekomsolutions/openmrs-cd/blob/0d7f989499c228767501e95b539fe83d1d4edda6/node-scripts/src/pipeline3/impl/dockerComposeFromArtifact.js#L94

2024-06-17 08:33 UTC, rbuisson requested changes

2024-06-17 08:39 UTC, enyachoke commented on node-scripts/src/pipeline3/impl/dockerComposeFromArtifact.js
> +      return this.getDeploymentScript(instanceDef);
I have made the change.

2024-06-17 08:46 UTC, rbuisson approved these changes

2024-06-18 15:01 UTC, merged